name: Build and Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure build
        run: bash configure.sh
      
      - name: Build application
        run: bash build.sh
      
      - name: Rename binaries
        run: |
          mv build/build-3ds/packaged/main.3dsx build/build-3ds/packaged/furcadia.3dsx
      
      - uses: actions/upload-artifact@v4
        with:
            name: Application
            path: |
                build/build-3ds/packaged/furcadia.3dsx
            if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`